### ISSUE TITLE
Install command needs to be updated in the repository.

### ISSUE THREAD

**Issue by bddenhartog** [folkswithhats/folkswithhats.org#8]
We *need* to:

- Update the displayed URI from `https://folkswithhats.org/fedy-installer` to `https://www.folkswithhats.org/fedy-installer`

We _should_:

- Rename the installer from `fedy-installer` to `installer` for brevity. There is nothing else that we provide an installer for currently.

- Remove the anchor tag (`<a>`) from the URI in the installation script. It shouldn't be downloaded directly, and if the user really wants to do that they can use `curl -o`. Instead, all the anchor tag does is cause an unnecessary download if the user happens to click on it.

- Refactor the displayed command to read `curl <path> | sudo bash`. There is nothing in the script that this should break, and it ran fine during testing.

**Comment by bugaevc** [comment]
> Update the displayed URI from https://folkswithhats.org/fedy-installer to https://www.folkswithhats.org/fedy-installer

Why?

> Refactor the displayed command to read curl <path> | sudo bash. There is nothing in the script that this should break, and it ran fine during testing.

What this did break for me when I was testing it is that when sudo asks for the password it reads the first line of the script instead of user's input. I worked around this by doing `sudo true; curl address | sudo bash`

But now that Fedora is betting big on Flatpak, wouldn't it be better if Fedy shipped as a Flatpak too? That would make the installation drastically easier (and it won't require root privileges, if you care about that); but we'll need some magic to run the scripts outside of the container.

**Comment by kwizart** [comment]
@bugaevc 

> But now that Fedora is betting big on Flatpak, wouldn't it be better if Fedy shipped as a Flatpak too? That would make the installation drastically easier (and it won't require root privileges, if you care about that); but we'll need some magic to run the scripts outside of the container.

As I understand, fedy cannot be provided as flatpak because most of it's tasks are related to tweaking the "host" system and not the container where fedy would reside. That been said, if you are interested in flatpak and ostree host (specially on workstation), there is a need to verify that fedy works as appropriate in this context.
The other point about flatpak is that many pre-built (proprietary or even floss) software that fedy installs; are provided by tarball and installed as root (maybe I'm wrong). Having theses software provided as flatpak would allow (if allowed to redistribute) a better means to install and run same (as they will be sandboxed).

**Comment by bugaevc** [comment]
> As I understand, fedy cannot be provided as flatpak because most of it's tasks are related to tweaking the "host" system and not the container where fedy would reside.

Flatpak has [HostCommand](https://github.com/flatpak/flatpak/blob/master/data/org.freedesktop.Flatpak.xml#L35-L61) specifically to allow this kind of usage. I suggest using Flatpak merely as a super convenient distribution format (compared to "`curl | sudo bash` this script"), not a sandboxing measure. Furthermore, installing a Flatpaked version of Fedy would not require root access at all (but using a plugin that needs root will - though we do that on-demand, with nice PolicyKit GUI prompts).
